Segundo Parcial Programacion Web III/SistemaDeGestionDeEquipos.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaDeGestionDeEquipos.Data.Entidades;
using SistemaDeGestionDeEquipos.Logica.Servicios;
using System.Diagnostics;

namespace SistemaDeGestionDeEquipos.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Segundo Parcial Programacion Web III/SistemaDeGestionDeEquipos.Web/Controllers/TorneoController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaDeGestionDeEquipos.Data.Entidades;
using SistemaDeGestionDeEquipos.Logica.Servicios;

namespace SistemaDeGestionDeEquipos.Web.Controllers
{
    public class TorneoController : Controller
    {

        private IJugadorServicio jugadorServicio;
        private IEquipoServicio equipoServicio;

        public TorneoController(ILogger<HomeController> logger, IJugadorServicio jugadorServicio, IEquipoServicio equipoServicio)
        {
            this.jugadorServicio = jugadorServicio;
            this.equipoServicio = equipoServicio;
        }

        [HttpGet]
        public IActionResult CrearJugador()
        {
            ViewBag.Equipos = this.equipoServicio.ListarEquipos();
            return View();
        }

        [HttpPost]
        public IActionResult CrearJugador(Jugador jugador)
        {
            ViewBag.Equipos = this.equipoServicio.ListarEquipos();

            if (!ModelState.IsValid)
                return View(jugador);

            this.jugadorServicio.CrearJugador(jugador);

            return RedirectToAction("ListarJugadores");
        }

        public IActionResult ListarJugadores(int? idEquipo)
        {
            ViewBag.IdEquipoElegido = idEquipo;
            ViewBag.Equipos = this.equipoServicio.ListarEquipos();

            if (idEquipo.HasValue)
            {
                var jugadores = this.jugadorServicio.ListarJugadoresPorEquipo(idEquipo.Value);
                return View(jugadores);
            }
            else
            {
                var jugadores = this.jugadorServicio.ListarJugadores();
                return View(jugadores);
            }
        }
    }
}

Segundo Parcial Programacion Web III/SistemaDeGestionDeEquipos.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Segundo Parcial Programacion Web III/SistemaDeGestionDeEquipos.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaDeGestionDeEquipos.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaDeGestionDeEquipos.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SistemaDeGestionDeEquipos.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Torneo" asp-action="CrearJugador">Crear Jugador</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Torneo" asp-action="ListarJugadores">Listar Jugadores</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SistemaDeGestionDeEquipos.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Segundo Parcial Programacion Web III/SistemaDeGestionDeEquipos.Web/Views/Torneo/CrearJugador.cshtml
@using SistemaDeGestionDeEquipos.Data.Entidades
@model SistemaDeGestionDeEquipos.Data.Entidades.Jugador

<form action="/Torneo/CrearJugador" method="post">

    <div class="form-group">
        <label for="NombreCompleto">Nombre Completo</label>
        <input type="text" class="form-control" id="NombreCompleto" name="NombreCompleto" placeholder="Nombre Completo">
    </div>

    <div>
        Equipo:
        <select name="IdEquipo">
            @foreach (Equipo equipo in ViewBag.Equipos)
            {
                <option value="@equipo.IdEquipo">@equipo.NombreEquipo</option>
            }
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Crear Jugador</button>

</form>

Segundo Parcial Programacion Web III/SistemaDeGestionDeEquipos.Web/Views/Torneo/ListarJugadores.cshtml
@using SistemaDeGestionDeEquipos.Data.Entidades
@model List<SistemaDeGestionDeEquipos.Data.Entidades.Jugador>

<form action="/Torneo/ListarJugadores" method="post">
    <div>
        Equipos:
        <select name="IdEquipo">
            <option value="">Todas</option>
            @foreach (Equipo equipo in ViewBag.Equipos)
            {
                if (ViewBag.IdEquipoElegido == equipo.IdEquipo)
                {
                    <option selected="selected" value="@equipo.IdEquipo">@equipo.NombreEquipo</option>
                }
                else
                {
                    <option value="@equipo.IdEquipo">@equipo.NombreEquipo</option>
                }
            }
        </select>
    </div>
    <button type="submit" class="btn btn-primary">Filtrar por equipos</button>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model[0].NombreCompleto)
            </th>
            <th>
                Equipo
            </th>
            <th>
                Nombre del Equipo
            </th>
        </tr>

        @foreach (var jugador in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => jugador.NombreCompleto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => jugador.IdEquipoNavigation.IdEquipo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => jugador.IdEquipoNavigation.NombreEquipo)
                </td>
            </tr>
        }
    </table>
</form>